version: '3.1'

services:
  demoweb:
    image: demoweb-images
    depends_on: 
      - webdb
    volumes:
      - /home/demo/docker_demo:/upload-dir
    environment:
      TZ: Asia/Shanghai
      MYSQL_HOST: webdb
      MYSQL_DATABASE: prod
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SPRING_PROFILES_ACTIVE: prod
    ports: 
      - "9300:8080"
      
  webdb:
    image: mysql:5.6
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci, --explicit_defaults_for_timestamp=1]
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prod
    ports: 
      - "3010:3306"